import Axios from "axios";


//for upload files
export default Axios.create({
  baseURL: "http://localhost:8080",
  headers: {
    "Content-type": "application/json",
  },
});
export const stringToColor = (string) => {
  let hash = 0;
  let color = "#";
  let i;

  for (i = 0; i < string.length; i += 1) {
    hash = string.charCodeAt(i) + ((hash << 5) - hash);
  }
  for (i = 0; i < 3; i += 1) {
    const value = (hash >> (i * 8)) & 0xff;
    color += `00${value.toString(16)}`.slice(-2);
  }

  return color;
};
export const stringAvatar = (name) => {
  return {
    sx: {
      bgcolor: stringToColor(name),
    },
    children: `${name.split(" ")[0][0]}`,
    // children: `${name.split(" ")[0][0]}${name.split(" ")[1][0]}`,
  };
};
export const roleList = [
  { label: "کاربر مالی", value: "10" },
  { label: "ریکاوریست", value: "20" },
  { label: "اپراتور رزرو", value: "30" },
];
export const stakeholderTypeList = [
  { label: "مسافر", value: "passenger" },
  { label: "راننده", value: "driver" },
  { label: "شرکت", value: "company" },
];
export const tripTabList = [
  { value: 0, label: "همه" },
  { value: 1, label: "رزرو شده" }, // status=1
  { value: 2, label: "منتظر اختصاص راننده" }, // می بایست سفرهایی نمایش داده شوند که در وضعیت تایید دریافت پیش پرداخت هستند و منتظر اختصاص راننده هستند
  { value: 3, label: "منتظر اعلام پایان سفر" }, //می بایست سفرهایی نمایش داده شوند که به راننده اختصاص داده شده اند و منتظر اعلام پایان سفر هستند
  { value: 4, label: "ریکاوری" }, //ارسال به مالی و ریکاوری status=4
  { value: 5, label: "مالی" },
  { value: 6, label: "آرشیو" },
];
export const tripStatus = [
  { value: 1, label: "رزرو شده" },
  { value: 2, label: "تایید دریافت پیش پرداخت" },
  { value: 3, label: "اختصاص راننده و شروع سفر" },
  { value: 4, label: "پایان سفر و درحال ریکاوری" },
  { value: 5, label: "مالی" },
  { value: 6, label: "آرشیو" },
];
export const paymentMethod = [
  { label: "فیش بانکی", value: "فیش بانکی" },
  { label: "درگاه پرداخت بانک ملت", value: "درگاه پرداخت بانک ملت" },
  {
    label: "درگاه پرداخت بانک سامان",
    value: "درگاه پرداخت بانک سامان",
  },
  { label: "درگاه پرداخت زرین پال", value: "درگاه پرداخت زرین پال" },
  { label: "پس پرداخت (قراردادی)", value: "پس پرداخت (قراردادی)" },
];
export const driverBankName = [
  { label: "بانک ملّی ایران", value: "بانک ملّی ایران" },
  { label: "بانک سپه", value: "بانک سپه" },
  { label: "بانک صنعت و معدن", value: "بانک صنعت و معدن" },
  { label: "بانک کشاورزی", value: "بانک کشاورزی" },
  { label: "بانک مسکن", value: "بانک مسکن" },
  { label: "بانک توسعه صادرات ایران", value: "بانک توسعه صادرات ایران" },
  { label: "بانک توسعه تعاون", value: "بانک توسعه تعاون" },
  { label: "پست بانک ایران", value: "پست بانک ایران" },
  { label: "بانک اقتصاد نوین", value: "بانک اقتصاد نوین" },
  { label: "بانک پارسیان", value: "بانک پارسیان" },
  { label: "بانک کارآفرین", value: "بانک کارآفرین" },
  { label: "بانک سامان", value: "بانک سامان" },
  { label: "بانک سینا", value: "بانک سینا" },
  { label: "بانک خاور میانه", value: "بانک خاور میانه" },
  { label: "بانک شهر", value: "بانک شهر" },
  { label: "بانک دی", value: "بانک دی" },
  { label: "بانک صادرات", value: "بانک صادرات" },
  { label: "بانک ملت", value: "بانک ملت" },
  { label: "بانک تجارت", value: "بانک تجارت" },
  { label: "بانک رفاه", value: "بانک رفاه" },
  { label: "بانک حکمت ایرانیان", value: "بانک حکمت ایرانیان" },
  { label: "بانک گردشگری", value: "بانک گردشگری" },
  { label: "بانک ایران زمین", value: "بانک ایران زمین" },
  { label: "بانک قوامین", value: "بانک قوامین" },
  { label: "بانک انصار", value: "بانک انصار" },
  { label: "بانک سرمایه", value: "بانک سرمایه" },
  { label: "بانک پاسارگاد", value: "بانک پاسارگاد" },
  { label: "بانک مشترک ایران-ونزوئلا", value: "بانک مشترک ایران-ونزوئلا" },
  { label: "بانک قرض‌الحسنه مهر ایران", value: "بانک قرض‌الحسنه مهر ایران" },
  { label: "بانک قرض‌الحسنه رسالت", value: "بانک قرض‌الحسنه رسالت" },
];
export const carCategory = [
  { label: "سواری داخلی", value: 1 },
  { label: "سواری ویژه  ( آریو - النترا)", value: 2 },
  { label: "سواری VIP ( کمری - Fluence )", value: 3 },
  { label: "ون عادی", value: 4 },
  { label: "ون VIP", value: 5 },
  { label: "مینی بوس", value: 6 },
  { label: "مینی بوس VIP", value: 7 },
  { label: "میدل باس", value: 8 },
  { label: "میدل باس VIP", value: 9 },
  { label: "اتوبوس", value: 10 },
  { label: "اتوبوس VIP", value: 11 },
];
export const drivingLimitCode = [
  {
    code: "1",
    label: "سواری شخصی- انتقال پدال گاز به سمت چپ- دنده اتوماتیک",
  },
  {
    code: "2",
    label:
      "سواری شخصی- انتقال پدال گاز به سمت چپ- دنده اتوماتیک- فرمان هیدرولیک",
  },
  {
    code: "3",
    label:
      "سواری شخصی- انتقال پدال گاز به سمت چپ- دنده اتوماتیک- فرمان هیدرولیک-نصب زائده روی فرمان (دسته گرد)",
  },
  {
    code: "4",
    label:
      "سواری شخصی- انتقال پدال گاز به سمت چپ- دنده اتوماتیک- فرمان هیدرولیک-نصب زائده روی فرمان (دسته یو شکل)",
  },
  {
    code: "5",
    label: "سواری شخصی- استفاده از پدال گاز و ترمز اصلاح شده مناسب",
  },
  {
    code: "6",
    label: "سواری شخصی- استفاده از پدال گاز و ترمز و کلاچ اصلاح شده مناسب",
  },
  { code: "7", label: "سواری شخصی- استفاده از پدال کلاچ اصلاح شده مناسب" },
  { code: "8", label: "قرار دادن اهرم ترمز پارک در سمت چپ" },
  { code: "9", label: "قرار دادن اهرم ترمز پارک در سمت راست" },
  { code: "10", label: "--- تعریف نشده! ---" },
  { code: "11", label: "سواری شخصی" },
  { code: "12", label: "سواری شخصی با نصب آرم مخصوص ناشنوایان" },
  { code: "13", label: "سواری شخصی دارای فرمان هیدرولیک" },
  { code: "14", label: "سواری شخصی دارای دنده اتوماتیک" },
  { code: "15", label: "سواری شخصی دنده اتوماتیک- فرمان هیدرولیک" },
  {
    code: "16",
    label: "سواری شخصی دنده اتوماتیک- فرمان هیدرولیک و نصب زائده روی فرمان",
  },
  { code: "17", label: "سواری شخصی با نصب آئینه مخصوص" },
  { code: "18", label: "سواری شخصی دارای کلاچ دستی" },
  { code: "19", label: "سواری شخصی دارای گاز و ترمز دستی" },
  { code: "20", label: "--- تعریف نشده! ---" },
  { code: "21", label: "سواری شخصی دارای کلاچ و گاز و ترمز دستی" },
  { code: "22", label: "سواری شخصی با نصب زائده روی فرمان" },
  { code: "23", label: "سواری شخصی دنده اتوماتیک با نصب زائده روی فرمان" },
  { code: "24", label: "سواری شخصی فرمان هیدرولیک با نصب زائده روی فرمان" },
  { code: "25", label: "سواری شخصی دنده اتوماتیک با گاز و ترمز دستی" },
  {
    code: "26",
    label: "سواری شخصی دنده اتوماتیک با گاز و ترمز دستی و نصب زائده روی فرمان",
  },
  { code: "27", label: "سواری شخصی با استفاده از صندلی اصلاح شده مناسب" },
  { code: "28", label: "موتورسیکلت سه چرخ" },
  { code: "29", label: "با خودرو خاص" },
  { code: "30", label: "--- تعریف نشده! ---" },
  { code: "31", label: "با عینک طبی" },
  { code: "32", label: "با لنز طبی" },
  { code: "33", label: "با سمعک" },
  { code: "34", label: "نصب زائده روی فرمان (دسته یو شکل)" },
  { code: "35", label: "استفاده از حفاظ پدال گاز و ترمز" },
  { code: "36", label: "استفاده از ترمز پارک برقی" },
  { code: "37", label: "نصب زیرپایی ثابت مناسب" },
  { code: "38", label: "استفاده از دستکش مناسب" },
  { code: "39", label: "استفاده از دسته دنده اصلاح شده مناسب" },
  { code: "40", label: "--- تعریف نشده! ---" },
  { code: "41", label: "رانندگی در محدوده شهری" },
  { code: "42", label: "رانندگی در روز" },
  { code: "43", label: "محدودیت سرعت در رانندگی (حداکثر 80 کیلومتر در ساعت)" },
  { code: "44", label: "محدودیت سرعت در رانندگی (حداکثر 90 کیلومتر در ساعت)" },
  { code: "45", label: "محدودیت سرعت در رانندگی (حداکثر 100 کیلومتر در ساعت)" },
  { code: "46", label: "استفاده از دست راست مصنوعی مکانیکی" },
  { code: "47", label: "استفاده از دست چپ مصنوعی مکانیکی" },
  { code: "48", label: "استفاده از دست راست مصنوعی الکترونیکی" },
  { code: "49", label: "استفاده از دست چپ مصنوعی الکترونیکی" },
  { code: "50", label: "--- تعریف نشده! ---" },
  {
    code: "51",
    label: "موتور سیکلت سه چرخ- ترمز جلو و عقب بصورت پایی- دنده اتوماتیک",
  },
  {
    code: "52",
    label: "موتور سیکلت سه چرخ- ترمز جلو و عقب بصورت دستی- دنده اتوماتیک",
  },
  { code: "53", label: "موتور سیکلت سه چرخ- دنده اتوماتیک" },
  { code: "54", label: "موتور سیکلت دو چرخ- دنده اتوماتیک" },
  { code: "55", label: "سواری شخصی- وانت شخصی" },
  { code: "56", label: "موتور سیکلت دو چرخ یا سه چرخ دنده اتوماتیک" },
  { code: "57", label: "موتور سیکلت دو چرخ یا سه چرخ دنده اتوماتیک تا 125cc" },
  { code: "58", label: "موتور سیکلت سه چرخ دنده اتوماتیک  تا 125cc" },
];
export const carPelakType = [
  { label: "عادی", value: 1 },
  { label: "تاکسی", value: 2 },
  { label: "دولتی", value: 3 },
  { label: "نظامی", value: 4 },
  { label: "مسافربری", value: 5 },
];

export const carFuelType = [
  { label: "بنزین", value: 1 },
  { label: "گاز طبیعی (CNG)", value: 2 },
  { label: "گازوئیل", value: 3 },
  { label: "دوگانه سوز(بنزین و گاز)", value: 4 },
  { label: "هیبرید(بنزین و برق)", value: 5 },
  { label: "برقی (شارژی)", value: 6 },
];
export const drivingLicenseType = [
  { label: "موتورسیکلت", value: "1" },
  { label: "پایه سوم- خودروهای سواری حداکثر تا 9 نفر", value: "2" },
  { label: "پایه دوم- خودروهای باربری حداکثر تا 6 تن", value: "3" },
  { label: "پایه یکم- خودروهای باربری بیش از 6 تن", value: "4" },
  { label: "ویژه", value: "5" },
];
export const carColor = [
  { label: "سبز", value: "سبز" },
  { label: "زرد", value: "زرد" },
  { label: "سفید", value: "سفید" },
  { label: "سیاه", value: "سیاه" },
  { label: "قرمز", value: "قرمز" },
  { label: "آبی", value: "آبی" },
  { label: "بژ", value: "بژ" },
  { label: "نارنجی", value: "نارنجی" },
];
export const carYearModel = [
  { label: "1402", value: 1402 },
  { label: "1401", value: 1401 },
  { label: "1400", value: 1400 },
  { label: "1399", value: 1399 },
  { label: "1398", value: 1398 },
  { label: "1397", value: 1397 },
  { label: "1396", value: 1396 },
  { label: "1395", value: 1395 },
  { label: "1394", value: 1394 },
  { label: "1393", value: 1393 },
  { label: "1392", value: 1392 },
  { label: "1391", value: 1391 },
  { label: "1390", value: 1390 },
  { label: "1389", value: 1389 },
  { label: "1388", value: 1388 },
  { label: "1387", value: 1387 },
  { label: "1386", value: 1386 },
  { label: "1385", value: 1385 },
  { label: "1384", value: 1384 },
  { label: "1383", value: 1383 },
  { label: "1382", value: 1382 },
  { label: "1381", value: 1381 },
  { label: "1380", value: 1380 },
];
export const carSystem = [
  { label: "پژو", value: "پژو" },
  { label: "پراید", value: "پراید" },
  { label: "رنو", value: "رنو" },
  { label: "دوو", value: "دوو" },
  { label: "سمند", value: "سمند" },
  { label: "تیبا", value: "تیبا" },
  { label: "کیا", value: "کیا" },
  { label: "هیوندای", value: "هیوندای" },
  { label: "آئودی", value: "آئودی" },
  { label: "آریو", value: "آریو" },
  { label: "آلفا رومئو", value: "آلفا رومئو" },
  { label: "اتوبیانکی", value: "اتوبیانکی" },
  { label: "swm", value: "swm" },
  { label: "استین", value: "استین" },
  { label: "اسمارت", value: "اسمارت" },
  { label: "اشکودا", value: "اشکودا" },
  { label: "الدزموبیل", value: "الدزموبیل" },
  { label: "ام جی", value: "ام جی" },
  { label: "ام وی ام", value: "ام وی ام" },
  { label: "اپل", value: "اپل" },
  { label: "ایسوزو", value: "ایسوزو" },
  { label: "اینفینیتی", value: "اینفینیتی" },
  { label: "BMW", value: "BMW" },
  { label: "بایک", value: "بایک" },
  { label: "ام وی ام", value: "ام وی ام" },
  { label: "برلیانس", value: "برلیانس" },
  { label: "بسترن", value: "بسترن" },
  { label: "بنتلی", value: "بنتلی" },
  { label: "بنز", value: "بنز" },
  { label: "برگوارد", value: "برگوارد" },
  { label: "بوگاتی", value: "بوگاتی" },
  { label: "بی وای دی", value: "بی وای دی" },
  { label: "بیوک", value: "بیوک" },
  { label: "تارا", value: "تارا" },
  { label: "دوج", value: "دوج" },
  { label: "دی اس", value: "دی اس" },
  { label: "دیگنیتی", value: "دیگنیتی" },
  { label: "رانا", value: "رانا" },
  { label: "راین", value: "راین" },
  { label: "رولز رویس", value: "رولز رویس" },
  { label: "روور", value: "روور" },
  { label: "ریگان", value: "ریگان" },
  { label: "زوتی", value: "زوتی" },
  { label: "سئات", value: "سئات" },
  { label: "سانگ سانگ", value: "سانگ سانگ" },
  { label: "ساینا", value: "ساینا" },
  { label: "سوبارو", value: "سوبارو" },
  { label: "سوزوکی", value: "سوزوکی" },
  { label: "سیتروئن", value: "سیتروئن" },
  { label: "سیناد", value: "سیناد" },
  { label: "شاهین", value: "شاهین" },
  { label: "شورلت", value: "شورلت" },
  { label: "فراری", value: "فراری" },
  { label: "فوتون", value: "فوتون" },
  { label: "فورد", value: "فورد" },
  { label: "فولکس", value: "فولکس" },
  { label: "فیات", value: "فیات" },
  { label: "فیدلیتی", value: "فیدلیتی" },
  { label: "لادا", value: "لادا" },
  { label: "لامبورگینی", value: "لامبورگینی" },
  { label: "لانچیا", value: "لانچیا" },
  { label: "لندرور", value: "لندرور" },
  { label: "لندمارک", value: "لندمارک" },
  { label: "لوبو", value: "لوبو" },
  { label: "لوتوس", value: "لوتوس" },
  { label: "لکسوس", value: "لکسوس" },
  { label: "لیفان", value: "لیفان" },
  { label: "لینکن", value: "لینکن" },
  { label: "مازراتی", value: "مازراتی" },
  { label: "مزدا", value: "مزدا" },
  { label: "میتسوبیشی", value: "میتسوبیشی" },
  { label: "مینی ماینر", value: "مینی ماینر" },
  { label: "نیسان", value: "نیسان" },
  { label: "هامر", value: "هامر" },
  { label: "هاوال", value: "هاوال" },
  { label: "هایما", value: "هایما" },
  { label: "هن تنگ", value: "هن تنگ" },
  { label: "هوندا", value: "هوندا" },
  { label: "هیلمن", value: "هیلمن" },
  { label: "ولوو", value: "ولوو" },
  { label: "پاژن", value: "پاژن" },
  { label: "پروتون", value: "پروتون" },
  { label: "پلیموث", value: "پلیموث" },
  { label: "پورشه", value: "پورشه" },
  { label: "پونتیانگ", value: "پونتیانگ" },
  { label: "پیکان", value: "پیکان" },
  { label: "چانگان", value: "چانگان" },
  { label: "چری", value: "چری" },
  { label: "کادیلاک", value: "کادیلاک" },
  { label: "کرایسلر", value: "کرایسلر" },
  { label: "کوپا", value: "کوپا" },
  { label: "کوییک", value: "کوییک" },
  { label: "گریت وال", value: "گریت وال" },
  { label: "گک گونو", value: "گک گونو" },
];
export const carType = [
  {
    type: "پژو",
    system: [
      { label: "205", value: "205" },
      { label: "301", value: "301" },
      { label: "306", value: "306" },
      { label: "307", value: "307" },
      { label: "308", value: "308" },
      { label: "406", value: "406" },
      { label: "407", value: "407" },
      { label: "504", value: "504" },
      { label: "508", value: "508" },
      { label: "605", value: "605" },
      { label: "607", value: "607" },
      { label: "806", value: "806" },
      { label: "2008", value: "2008" },
      { label: "206 تیپ 1", value: "206 تیپ 1" },
      { label: "206 تیپ 2", value: "206 تیپ 2" },
      { label: "206 تیپ 3", value: "206 تیپ 3" },
      { label: "206 تیپ 5", value: "206 تیپ 5" },
      { label: "206 تیپ 6", value: "206 تیپ 6" },
      { label: "207 اتوماتیک", value: "207 اتوماتیک" },
      { label: "207 دنده ای", value: "207 دنده ای" },
      { label: "207 صندوقدار", value: "207 صندوقدار" },
      { label: "301 (3 سیلندر)", value: "301 (3 سیلندر)" },
      { label: "405 GL", value: "405 GL" },
      { label: "405 GLI", value: "405 GLI" },
      { label: "405 GLX", value: "405 GLX" },
      { label: "405 SLX", value: "405 SLX" },
      { label: "405 استیشن", value: "405 استیشن" },
      { label: "RCZ", value: "RCZ" },
      { label: "RD", value: "RD" },
      { label: "Roa", value: "Roa" },
      { label: "Roa G2", value: "Roa G2" },
      { label: "SD V1", value: "SD V1" },
      { label: "SD V2", value: "SD V2" },
      { label: "SD V20", value: "SD V20" },
      { label: "SD V8", value: "SD V8" },
      { label: "SD V9", value: "SD V9" },
      { label: "پارس", value: "پارس" },
      { label: "پارس ELX", value: "پارس ELX" },
      { label: "پارس LX", value: "پارس LX" },
      { label: "پارس اتوماتیک", value: "پارس اتوماتیک" },
    ],
  },
  {
    type: "پراید",
    system: [
      { label: "131", value: "131" },
      { label: "132", value: "132" },
      { label: "141", value: "141" },
    ],
  },
  {
    type: "رنو",
    system: [
      { label: "اسکالا", value: "اسکالا" },
      { label: "اسکالا کروک", value: "اسکالا کروک" },
      { label: "پارس تندر", value: "پارس تندر" },
      { label: "پی کی", value: "پی کی" },
      { label: "تالیسمان", value: "تالیسمان" },
      { label: "تندر 90 E0", value: "تندر 90 E0" },
      { label: "تندر 90 E1", value: "تندر 90 E1" },
      { label: "تندر 90 E2", value: "تندر 90 E2" },
      { label: "تندر 90 استیشن", value: "تندر 90 استیشن" },
      { label: "تندر پلاس", value: "تندر پلاس" },
      { label: "تندر پلاس اتوماتیک", value: "تندر پلاس اتوماتیک" },
      { label: "تندر90 اتوماتیک", value: "تندر90 اتوماتیک" },
      { label: "داستر", value: "داستر" },
      { label: "رنو 21", value: "رنو 21" },
      { label: "ساندرو اتوماتیک", value: "ساندرو اتوماتیک" },
      {
        label: "ساندرو استپ وی (اتوماتیک)",
        value: "ساندرو استپ وی (اتوماتیک)",
      },
      { label: "ساندرو استپ وی (دنده ای)", value: "ساندرو استپ وی (دنده ای)" },
      { label: "ساندرو دنده ای", value: "ساندرو دنده ای" },
      { label: "سپند", value: "سپند" },
      { label: "سفران 2.0", value: "سفران 2.0" },
      { label: "سفران 2.5", value: "سفران 2.5" },
      { label: "سیمبل", value: "سیمبل" },
      { label: "فلوئنس", value: "فلوئنس" },
      { label: "کپچر", value: "کپچر" },
      { label: "کلیو", value: "کلیو" },
      { label: "کولیوس", value: "کولیوس" },
      { label: "لاگونا کوپه", value: "لاگونا کوپه" },
      { label: "لاگونا کوپه", value: "لاگونا کوپه" },
      { label: "لتیتود", value: "لتیتود" },
      { label: "مگان 1600", value: "مگان 1600" },
      { label: "مگان 2000", value: "مگان 2000" },
      { label: "مگان کروک", value: "مگان کروک" },
      { label: "مگان هاچ بک", value: "مگان هاچ بک" },
    ],
  },
  {
    type: "سمند",
    system: [
      { label: "EL", value: "EL" },
      { label: "LX", value: "LX" },
      { label: "LX EF7", value: "LX EF7" },
      { label: "SE", value: "SE" },
      { label: "X7", value: "X7" },
      { label: "سریر", value: "سریر" },
      { label: "سورن", value: "سورن" },
      { label: "سورن EF7", value: "سورن EF7" },
      { label: "سورن ELX توربو", value: "سورن ELX توربو" },
    ],
  },
  {
    type: "تیبا",
    system: [
      { label: "تیبا صندوق دار", value: "تیبا صندوق دار" },
      { label: "تیبا 2", value: "تیبا 2" },
    ],
  },
  {
    type: "کیا",
    system: [
      { label: "اپتیما (۴ سیلندر)", value: "اپتیما (۴ سیلندر)" },
      { label: "اپتیما (۶ سیلندر)", value: "اپتیما (۶ سیلندر)" },
      { label: "اپتیما GT", value: "اپتیما GT" },
      { label: "اپتیما JF", value: "اپتیما JF" },
      { label: "اپتیما TF", value: "اپتیما TF" },
      { label: "اپتیما هیبرید", value: "اپتیما هیبرید" },
      { label: "اپیروس", value: "اپیروس" },
      { label: "اسپورتیج (۴ سیلندر)", value: "اسپورتیج (۴ سیلندر)" },
      { label: "اسپورتیج (۶ سیلندر)", value: "اسپورتیج (۶ سیلندر)" },
      { label: "پیکانتو", value: "پیکانتو" },
      { label: "ریو (مونتاژ)", value: "ریو (مونتاژ)" },
      { label: "ریو 5", value: "ریو 5" },
      { label: "ریو 5 هاچ بک", value: "ریو 5 هاچ بک" },
      { label: "سراتو 1600", value: "سراتو 1600" },
      { label: "سراتو 2000", value: "سراتو 2000" },
      { label: "سراتو کوپه", value: "سراتو کوپه" },
      { label: "سورنتو (۴ سیلندر)", value: "سورنتو (۴ سیلندر)" },
      { label: "سورنتو (۶ سیلندر)", value: "سورنتو (۶ سیلندر)" },
      { label: "سول", value: "سول" },
      { label: "کادنزا", value: "کادنزا" },
      { label: "کارناوال", value: "کارناوال" },
      { label: "کارنز", value: "کارنز" },
      { label: "کوریس", value: "کوریس" },
      { label: "موهاوی V6", value: "موهاوی V6" },
      { label: "موهاوی V8", value: "موهاوی V8" },
    ],
  },
  {
    type: "هیوندای",
    system: [
      { label: "i10", value: "i10" },
      { label: "i20", value: "i20" },
      { label: "i30", value: "i30" },
      { label: "i40", value: "i40" },
      { label: "i40 استیشن", value: "i40 استیشن" },
      { label: "ix35", value: "ix35" },
      { label: "ix55", value: "ix55" },
      { label: "اسکوپ", value: "اسکوپ" },
      { label: "اکسل", value: "اکسل" },
      { label: "اکسنت", value: "اکسنت" },
      { label: "النترا", value: "النترا" },
      { label: "آزرا (۴ سیلندر)", value: "آزرا (۴ سیلندر)" },
      { label: "آزرا (۶ سیلندر)", value: "آزرا (۶ سیلندر)" },
      { label: "آوانته", value: "آوانته" },
      { label: "توسان (۴ سیلندر)", value: "توسان (۴ سیلندر)" },
      { label: "توسان (۶ سیلندر)", value: "توسان (۶ سیلندر)" },
      { label: "جنسیس", value: "جنسیس" },
      { label: "جنسیس کوپه", value: "جنسیس کوپه" },
      { label: "سانتافه (۴ سیلندر)", value: "سانتافه (۴ سیلندر)" },
      { label: "سانتافه (۶ سیلندر)", value: "سانتافه (۶ سیلندر)" },
      { label: "سنتنیال", value: "سنتنیال" },
      { label: "سوناتا (۴ سیلندر)", value: "سوناتا (۴ سیلندر)" },
      { label: "سوناتا (۶ سیلندر)", value: "سوناتا (۶ سیلندر)" },
      { label: "سوناتا LF", value: "سوناتا LF" },
      { label: "سوناتا هیبرید", value: "سوناتا هیبرید" },
      { label: "کوپه", value: "کوپه" },
      { label: "وراکروز", value: "وراکروز" },
      { label: "ورنا", value: "ورنا" },
      { label: "ولستر", value: "ولستر" },
    ],
  },
  {
    type: "آئودی",
    system: [
      { label: "A4", value: "A4" },
      { label: "A5", value: "A5" },
      { label: "A6", value: "A6" },
      { label: "A7", value: "A7" },
      { label: "A8", value: "A8" },
      { label: "Q3", value: "Q3" },
      { label: "Q5", value: "Q5" },
      { label: "Q7", value: "Q7" },
      { label: "R8", value: "R8" },
      { label: "RS4", value: "RS4" },
      { label: "S6", value: "S6" },
      { label: "TT", value: "TT" },
      { label: "TT کروک", value: "TT کروک" },
      { label: "آئودی 100", value: "آئودی 100" },
    ],
  },
  {
    type: "آریو",
    system: [
      { label: "1.5 دنده ای", value: "1.5 دنده ای" },
      { label: "1.6 اتوماتیک", value: "1.6 اتوماتیک" },
      { label: "1.6 دنده ای", value: "1.6 دنده ای" },
    ],
  },
  {
    type: "آلفا رومئو",
    system: [
      { label: "4C", value: "4C" },
      { label: "آلفتا", value: "آلفتا" },
      { label: "جولیتا", value: "جولیتا" },
      { label: "میتو", value: "میتو" },
    ],
  },
  { type: "اتوبیانکی", system: [{ label: "a112", value: "a112" }] },
  {
    type: "swm",
    system: [
      { label: "G01", value: "G01" },
      { label: "G01F", value: "G01F" },
    ],
  },
  {
    type: "استین",
    system: [
      { label: "چمپ", value: "چمپ" },
      { label: "دوون", value: "دوون" },
      { label: "سون", value: "سون" },
      { label: "کمبریج", value: "کمبریج" },
      { label: "مترو پلیتن", value: "مترو پلیتن" },
    ],
  },
  {
    type: "اسمارت",
    system: [
      { label: "RAV4", value: "RAV4" },
      { label: "رودستر", value: "رودستر" },
      { label: "فور 2", value: "فور 2" },
    ],
  },
  {
    type: "اشکودا",
    system: [{ label: "اکتاویا", value: "اکتاویا" }],
  },
  {
    type: "الدزموبیل",
    system: [
      { label: "ریجنسی", value: "ریجنسی" },
      { label: "کاتلاس", value: "کاتلاس" },
      { label: "کاتلاس سیرا", value: "کاتلاس سیرا" },
    ],
  },
  {
    type: "ام جی",
    system: [
      { label: "3", value: "3" },
      { label: "6", value: "6" },
      { label: "350", value: "350" },
      { label: "360", value: "360" },
      { label: "550", value: "550" },
      { label: "GS", value: "GS" },
      { label: "GT", value: "GT" },
      { label: "RX5", value: "RX5" },
      { label: "ZS", value: "ZS" },
    ],
  },
  {
    type: "ام وی ام",
    system: [
      { label: "315 هاچ بک", value: "315 هاچ بک" },
      { label: "530", value: "530" },
      { label: "550", value: "550" },
      { label: "110 (۳ سیلندر)", value: "110 (۳ سیلندر)" },
      { label: "110 (۴ سیلندر)", value: "110 (۴ سیلندر)" },
      { label: "110S (۳ سیلندر)", value: "110S (۳ سیلندر)" },
      { label: "315 صندوق دار", value: "315 صندوق دار" },
      { label: "A15", value: "A15" },
      { label: "x22", value: "x22" },
      { label: "X33", value: "X33" },
      { label: "X55", value: "X55" },
      { label: "آریزو 5", value: "آریزو 5" },
      { label: "آریزو 6", value: "آریزو 6" },
      { label: "تیگو 5", value: "تیگو 5" },
      { label: "تیگو 7", value: "تیگو 7" },
      { label: "ویانا", value: "ویانا" },
    ],
  },
  {
    type: "اپل",
    system: [
      { label: "GT", value: "GT" },
      { label: "امگا (۴ سیلندر)", value: "امگا (۴ سیلندر)" },
      { label: "امگا (۶ سیلندر)", value: "امگا (۶ سیلندر)" },
      { label: "اینسیگنیا", value: "اینسیگنیا" },
      { label: "آسترا سدان", value: "آسترا سدان" },
      { label: "آسترا هاچ بک", value: "آسترا هاچ بک" },
      { label: "رکورد", value: "رکورد" },
      { label: "زافیرا", value: "زافیرا" },
      { label: "فرانترا", value: "فرانترا" },
      { label: "کاپیتان", value: "کاپیتان" },
      { label: "کالیبرا", value: "کالیبرا" },
      { label: "کورسا اتوماتیک", value: "کورسا اتوماتیک" },
      { label: "کورسا دنده ای", value: "کورسا دنده ای" },
      { label: "موکا", value: "موکا" },
      { label: "وکترا", value: "وکترا" },
    ],
  },
  {
    type: "ایسوزو",
    system: [
      { label: "تروپر", value: "تروپر" },
      { label: "جمینی", value: "جمینی" },
      { label: "رودیو", value: "رودیو" },
    ],
  },
  {
    type: "اینفینیتی",
    system: [
      { label: "EX", value: "EX" },
      { label: "FX", value: "FX" },
      { label: "Q30", value: "Q30" },
      { label: "Q50", value: "Q50" },
      { label: "Q60", value: "Q60" },
      { label: "Q70", value: "Q70" },
      { label: "QX50", value: "QX50" },
      { label: "QX60", value: "QX60" },
      { label: "QX70", value: "QX70" },
      { label: "QX80", value: "QX80" },
    ],
  },
  {
    type: "BMW",
    system: [
      { label: "518", value: "518" },
      { label: "2002", value: "2002" },
      { label: "116i", value: "116i" },
      { label: "118i", value: "118i" },
      { label: "120i", value: "120i" },
      { label: "120i کروک", value: "120i کروک" },
      { label: "120i کوپه", value: "120i کوپه" },
      { label: "125i", value: "125i" },
      { label: "125i کروک", value: "125i کروک" },
      { label: "125i کوپه", value: "125i کوپه" },
      { label: "135i کروک", value: "135i کروک" },
      { label: "135i کوپه", value: "135i کوپه" },
      { label: "218i", value: "218i" },
      { label: "220i کروک", value: "220i کروک" },
      { label: "220i کوپه", value: "220i کوپه" },
      { label: "225i", value: "225i" },
      { label: "230i کروک", value: "230i کروک" },
      { label: "230i کوپه", value: "230i کوپه" },
      { label: "316i", value: "316i" },
      { label: "318i", value: "318i" },
      { label: "318i کروک", value: "318i کروک" },
      { label: "318i کوپه", value: "318i کوپه" },
      { label: "320i", value: "320i" },
      { label: "320i GT", value: "320i GT" },
      { label: "320i کروک", value: "320i کروک" },
      { label: "320i کوپه", value: "320i کوپه" },
      { label: "325i", value: "325i" },
      { label: "325i کروک", value: "325i کروک" },
      { label: "325i کوپه", value: "325i کوپه" },
      { label: "328i", value: "328i" },
      { label: "328i GT", value: "328i GT" },
      { label: "330i (چهارسیلندر)", value: "330i (چهارسیلندر)" },
      { label: "330i (شش سیلندر)", value: "330i (شش سیلندر)" },
      { label: "330i کروک", value: "330i کروک" },
      { label: "330i کوپه", value: "330i کوپه" },
      { label: "335i", value: "335i" },
      { label: "335i کروک", value: "335i کروک" },
      { label: "335i کوپه", value: "335i کوپه" },
      { label: "420i", value: "420i" },
      { label: "420i کوپه", value: "420i کوپه" },
      { label: "428i", value: "428i" },
      { label: "428i کروک", value: "428i کروک" },
      { label: "428i گرن کوپه", value: "428i گرن کوپه" },
      { label: "520i (۴ سیلندر)", value: "520i (۴ سیلندر)" },
      { label: "520i (۶ سیلندر)", value: "520i (۶ سیلندر)" },
      { label: "523i", value: "523i" },
      { label: "525i", value: "525i" },
      { label: "528i", value: "528i" },
      { label: "528i GT", value: "528i GT" },
      { label: "530i (چهارسیلندر)", value: "530i (چهارسیلندر)" },
      { label: "530i (شش سیلندر)", value: "530i (شش سیلندر)" },
      { label: "530xi", value: "530xi" },
      { label: "535i", value: "535i" },
      { label: "535i GT", value: "535i GT" },
      { label: "540i", value: "540i" },
      { label: "545i", value: "545i" },
      { label: "550i", value: "550i" },
      { label: "630i کروک", value: "630i کروک" },
      { label: "630i کوپه", value: "630i کوپه" },
      { label: "633-CSI", value: "633-CSI" },
      { label: "635i", value: "635i" },
      { label: "635i-CSI", value: "635i-CSI" },
      { label: "640i", value: "640i" },
      { label: "645i", value: "645i" },
      { label: "650i کروک", value: "650i کروک" },
      { label: "650i کوپه", value: "650i کوپه" },
      { label: "650i گرن کوپه", value: "650i گرن کوپه" },
      { label: "730 Li (۴ سیلندر)", value: "730 Li (۴ سیلندر)" },
      { label: "730 Li (۶ سیلندر)", value: "730 Li (۶ سیلندر)" },
      { label: "730i (۴ سیلندر)", value: "730i (۴ سیلندر)" },
      { label: "730i (۶ سیلندر)", value: "730i (۶ سیلندر)" },
      { label: "733i", value: "733i" },
      { label: "735i", value: "735i" },
      { label: "735li", value: "735li" },
      { label: "740i", value: "740i" },
      { label: "740Li", value: "740Li" },
      { label: "745li", value: "745li" },
      { label: "750i", value: "750i" },
      { label: "750li", value: "750li" },
      { label: "760li", value: "760li" },
      { label: "850i", value: "850i" },
      { label: "CS 3.0", value: "CS 3.0" },
      { label: "i8", value: "i8" },
      { label: "m3", value: "m3" },
      { label: "m3 کروک", value: "m3 کروک" },
      { label: "m3 کوپه", value: "m3 کوپه" },
      { label: "m4", value: "m4" },
      { label: "m5", value: "m5" },
      { label: "m6", value: "m6" },
      { label: "X1", value: "X1" },
      { label: "X1 1.8", value: "X1 1.8" },
      { label: "X1 2.0", value: "X1 2.0" },
      { label: "X1 2.8", value: "X1 2.8" },
      { label: "X3 2.0", value: "X3 2.0" },
      { label: "X3 2.5", value: "X3 2.5" },
      { label: "X3 2.8", value: "X3 2.8" },
      { label: "X3 3.0", value: "X3 3.0" },
      { label: "X3 3.5", value: "X3 3.5" },
      { label: "X4 2.8", value: "X4 2.8" },
      { label: "X5 3.5", value: "X5 3.5" },
      { label: "X5 5.0", value: "X5 5.0" },
      { label: "X6 3.5", value: "X6 3.5" },
      { label: "X6 5.0", value: "X6 5.0" },
      { label: "Z3", value: "Z3" },
      { label: "Z4 2.0", value: "Z4 2.0" },
      { label: "Z4 2.8", value: "Z4 2.8" },
      { label: "Z4 3.5", value: "Z4 3.5" },
    ],
  },
  {
    type: "بایک",
    system: [
      { label: "X25", value: "X25" },
      { label: "سابرینا هاچ بک", value: "سابرینا هاچ بک" },
      { label: "سنوا", value: "سنوا" },
    ],
  },
  {
    type: "برلیانس",
    system: [
      { label: "H220", value: "H220" },
      { label: "H230", value: "H230" },
      { label: "H320", value: "H320" },
      { label: "H330", value: "H330" },
      { label: "V5", value: "V5" },
      { label: "کراس C3", value: "کراس C3" },
    ],
  },
  {
    type: "بسترن",
    system: [
      { label: "H220", value: "H220" },
      { label: "H230", value: "H230" },
      { label: "H320", value: "H320" },
      { label: "H330", value: "H330" },
      { label: "V5", value: "V5" },
      { label: "کراس C3", value: "کراس C3" },
    ],
  },
  {
    type: "بنتلی",
    system: [
      { label: "بنتایگا", value: "بنتایگا" },
      { label: "کنتینانتال", value: "کنتینانتال" },
      { label: "کنتینانتال GT", value: "کنتینانتال GT" },
      { label: "مولسان", value: "مولسان" },
    ],
  },
  {
    type: "بنز",
    system: [
      { label: "A150", value: "A150" },
      { label: "A160", value: "A160" },
      { label: "A170", value: "A170" },
      { label: "A180", value: "A180" },
      { label: "A200", value: "A200" },
      { label: "A200 Turbo", value: "A200 Turbo" },
      { label: "B150", value: "B150" },
      { label: "B160", value: "B160" },
      { label: "B170", value: "B170" },
      { label: "B180", value: "B180" },
      { label: "B200", value: "B200" },
      { label: "B200 Turbo", value: "B200 Turbo" },
      { label: "C180", value: "C180" },
      { label: "C190", value: "C190" },
      { label: "C200", value: "C200" },
      { label: "C220", value: "C220" },
      { label: "C230 (۴ سیلندر)", value: "C230 (۴ سیلندر)" },
      { label: "C230 (۶ سیلندر)", value: "C230 (۶ سیلندر)" },
      { label: "C240", value: "C240" },
      { label: "C250", value: "C250" },
      { label: "C250 کوپه", value: "C250 کوپه" },
      { label: "C280", value: "C280" },
      { label: "C300", value: "C300" },
      { label: "C320", value: "C320" },
      { label: "C350", value: "C350" },
      { label: "C350 کوپه", value: "C350 کوپه" },
      { label: "C63", value: "C63" },
      { label: "CE230", value: "CE230" },
      { label: "CE280", value: "CE280" },
      { label: "CL500", value: "CL500" },
      { label: "CL600", value: "CL600" },
      { label: "CL65", value: "CL65" },
      { label: "CLA180", value: "CLA180" },
      { label: "CLA200", value: "CLA200" },
      { label: "CLA250", value: "CLA250" },
      { label: "CLA45", value: "CLA45" },
      { label: "CLK 200", value: "CLK 200" },
      { label: "CLK200 کروک", value: "CLK200 کروک" },
      { label: "CLK200 کوپه", value: "CLK200 کوپه" },
      { label: "CLK240 کروک", value: "CLK240 کروک" },
      { label: "CLK240 کوپه", value: "CLK240 کوپه" },
      { label: "CLK280 کروک", value: "CLK280 کروک" },
      { label: "CLK280 کوپه", value: "CLK280 کوپه" },
      { label: "CLK320 کروک", value: "CLK320 کروک" },
      { label: "CLK320 کوپه", value: "CLK320 کوپه" },
      { label: "CLK350 کروک", value: "CLK350 کروک" },
      { label: "CLK350 کوپه", value: "CLK350 کوپه" },
      { label: "CLS350", value: "CLS350" },
      { label: "CLS550", value: "CLS550" },
      { label: "CLS500", value: "CLS500" },
      { label: "CLS63", value: "CLS63" },
      { label: "E190", value: "E190" },
      { label: "E200", value: "E200" },
      { label: "E200 (مونتاژ)", value: "کراس C3" },
      { label: "E200 کروک", value: "E200 کروک" },
      { label: "E220", value: "E220" },
      { label: "E230 (۴ سیلندر)", value: "E230 (۴ سیلندر)" },
      { label: "E230 (۶ سیلندر)", value: "E230 (۶ سیلندر)" },
      { label: "E230 (مونتاژ)", value: "E230 (مونتاژ)" },
      { label: "E240", value: "E240" },
      { label: "E250", value: "E250" },
      { label: "E260", value: "E260" },
      { label: "E280", value: "E280" },
      { label: "E280 (مونتاژ)", value: "E280 (مونتاژ)" },
      { label: "E300", value: "E300" },
      { label: "E320", value: "E320" },
      { label: "E350", value: "E350" },
      { label: "E350 (مونتاژ)", value: "E350 (مونتاژ)" },
      { label: "E350 کروک", value: "E350 کروک" },
      { label: "E350 کوپه", value: "E350 کوپه" },
      { label: "E55", value: "E55" },
      { label: "E63", value: "E63" },
      { label: "G230", value: "G230" },
      { label: "G280", value: "G280" },
      { label: "G350", value: "G350" },
      { label: "G500", value: "G500" },
      { label: "GL550", value: "GL550" },
      { label: "GL63", value: "GL63" },
      { label: "GLA 200", value: "GLA 200" },
      { label: "GLA250", value: "GLA250" },
      { label: "GLA45", value: "GLA45" },
      { label: "GLC250", value: "GLC250" },
      { label: "GLC300", value: "GLC300" },
      { label: "GLE350", value: "GLE350" },
      { label: "GLK250", value: "GLK250" },
      { label: "GLK280", value: "GLK280" },
      { label: "GLK300", value: "GLK300" },
      { label: "GLK350", value: "GLK350" },
      { label: "GTS", value: "GTS" },
      { label: "ML320", value: "ML320" },
      { label: "ML350", value: "ML350" },
      { label: "ML500", value: "ML500" },
      { label: "ML63", value: "ML63" },
      { label: "S250", value: "S250" },
      { label: "S280", value: "S280" },
      { label: "S300", value: "S300" },
      { label: "S320", value: "S320" },
      { label: "S350", value: "S350" },
      { label: "S450", value: "S450" },
      { label: "S500", value: "S500" },
      { label: "S550", value: "S550" },
      { label: "S600", value: "S600" },
      { label: "S63", value: "S63" },
      { label: "S65", value: "S65" },
      { label: "SE280", value: "SE280" },
      { label: "SE300", value: "SE300" },
      { label: "SE450", value: "SE450" },
      { label: "SE500", value: "SE500" },
      { label: "SE560", value: "SE560" },
      { label: "SEC560", value: "SEC560" },
      { label: "SL350", value: "SL350" },
      { label: "SL450", value: "SL450" },
      { label: "SL500", value: "SL500" },
      { label: "SL550", value: "SL550" },
      { label: "SL600", value: "SL600" },
      { label: "SL650", value: "SL650" },
      { label: "SLC280", value: "SLC280" },
      { label: "SLC350", value: "SLC350" },
      { label: "SLC450", value: "SLC450" },
      { label: "SLC500", value: "SLC500" },
      { label: "SLK200", value: "SLK200" },
      { label: "SLK230", value: "SLK230" },
      { label: "SLK250", value: "SLK250" },
      { label: "SLK280", value: "SLK280" },
      { label: "SLK350", value: "SLK350" },
      { label: "SLK55", value: "SLK55" },
      { label: "SLR", value: "SLR" },
      { label: "SLS", value: "SLS" },
    ],
  },
  {
    type: "برگوارد",
    system: [
      { label: "BX5", value: "BX5" },
      { label: "BX7", value: "BX7" },
      { label: "کراس C3", value: "کراس C3" },
    ],
  },
  {
    type: "بوگاتی",
    system: [
      { label: "شیرون", value: "شیرون" },
      { label: "ویرون", value: "ویرون" },
    ],
  },
  {
    type: "بی وای دی",
    system: [
      { label: "F3", value: "F3" },
      { label: "S6", value: "S6" },
      { label: "S7", value: "S7" },
    ],
  },
  {
    type: "بیوک",
    system: [
      { label: "B2", value: "B2" },
      { label: "B3", value: "B3" },
      { label: "B4", value: "B4" },
      { label: "اسکای لارک", value: "اسکای لارک" },
      { label: "اسکای هاوک", value: "اسکای هاوک" },
      { label: "الکترا", value: "الکترا" },
      { label: "آپولو", value: "آپولو" },
      { label: "پارک اونیو", value: "پارک اونیو" },
      { label: "رگال", value: "رگال" },
      { label: "رودمستر", value: "رودمستر" },
      { label: "ریویرا", value: "ریویرا" },
      { label: "سایر", value: "سایر" },
      { label: "سنچری", value: "سنچری" },
      { label: "لسابر", value: "لسابر" },
    ],
  },
  {
    type: "تارا",
    system: [
      { label: "اتوماتیک", value: "اتوماتیک" },
      { label: "دنده ای", value: "دنده ای" },
    ],
  },
  {
    type: "دوج",
    system: [
      { label: "اسپن", value: "اسپن" },
      { label: "اونجر", value: "اونجر" },
      { label: "باراکودا", value: "باراکودا" },
      { label: "برادرز", value: "برادرز" },
      { label: "جرنی", value: "جرنی" },
      { label: "چارجر", value: "چارجر" },
      { label: "چلنجر", value: "چلنجر" },
      { label: "دارت", value: "دارت" },
      { label: "دورانگو", value: "دورانگو" },
      { label: "دیپلمات", value: "دیپلمات" },
      { label: "چارجر", value: "چارجر" },
      { label: "رم چارجر", value: "رم چارجر" },
      { label: "کرنت", value: "کرنت" },
      { label: "موناکو", value: "موناکو" },
      { label: "نیویورکر", value: "نیویورکر" },
      { label: "وایپر", value: "وایپر" },
    ],
  },
  {
    type: "دوو",
    system: [
      { label: "اسپرو", value: "اسپرو" },
      { label: "ریسر", value: "ریسر" },
      { label: "سیلو", value: "سیلو" },
      { label: "ماتیز", value: "ماتیز" },
      { label: "نوبیرا", value: "نوبیرا" },
    ],
  },
  {
    type: "دی اس",
    system: [
      { label: "3", value: "3" },
      { label: "5", value: "5" },
      { label: "6", value: "6" },
      { label: "4 کراس بک", value: "4 کراس بک" },
      { label: "5LS", value: "5LS" },
      { label: "7 کراس بک", value: "7 کراس بک" },
    ],
  },
  {
    type: "دیگنیتی",
    system: [{ label: "دیگنیتی", value: "دیگنیتی" }],
  },
  {
    type: "رانا",
    system: [
      { label: "EL", value: "EL" },
      { label: "LX", value: "LX" },
      { label: "پلاس", value: "پلاس" },
    ],
  },
  {
    type: "راین",
    system: [{ label: "راین", value: "راین" }],
  },
  {
    type: "رولز رویس",
    system: [
      { label: "ریس", value: "ریس" },
      { label: "فانتوم", value: "فانتوم" },
      { label: "کورنیش", value: "کورنیش" },
      { label: "گوست", value: "گوست" },
    ],
  },
  {
    type: "روور",
    system: [{ label: "روور", value: "روور" }],
  },
  {
    type: "ریگان",
    system: [
      { label: "رویال", value: "رویال" },
      { label: "فلگشیپ", value: "فلگشیپ" },
    ],
  },
  {
    type: "زوتی",
    system: [
      { label: "S300", value: "S300" },
      { label: "سایر", value: "سایر" },
    ],
  },
  {
    type: "سئات",
    system: [
      { label: "آلتا", value: "آلتا" },
      { label: "ایبیزا", value: "ایبیزا" },
      { label: "لئون", value: "لئون" },
    ],
  },
  {
    type: "سانگ سانگ",
    system: [
      { label: "اکتیون", value: "اکتیون" },
      { label: "اکتیون اسپرت", value: "اکتیون اسپرت" },
      { label: "تیوولی", value: "تیوولی" },
      { label: "چیرمن 500", value: "چیرمن 500" },
      { label: "چیرمن 600", value: "چیرمن 600" },
      { label: "رکستون", value: "رکستون" },
      { label: "رودیوس", value: "رودیوس" },
      { label: "کایرون", value: "کایرون" },
      { label: "کوراندو (۴ سیلندر)", value: "کوراندو (۴ سیلندر)" },
      { label: "کوراندو (۶ سیلندر)", value: "کوراندو (۶ سیلندر)" },
      { label: "موسو (۴ سیلندر)", value: "موسو (۴ سیلندر)" },
      { label: "ایبیزا", value: "ایبیزا" },
      { label: "موسو (۶ سیلندر)", value: "موسو (۶ سیلندر)" },
      { label: "نیو اکتیون", value: "نیو اکتیون" },
      { label: "نیو کوراندو", value: "نیو کوراندو" },
    ],
  },
  {
    type: "ساینا",
    system: [
      { label: "EX", value: "EX" },
      { label: "SX", value: "SX" },
      { label: "اتوماتیک", value: "اتوماتیک" },
    ],
  },
  {
    type: "سوبارو",
    system: [
      { label: "XV", value: "XV" },
      { label: "BRZ", value: "BRZ" },
      { label: "فارستر", value: "فارستر" },
      { label: "لگاسی", value: "لگاسی" },
    ],
  },
  {
    type: "سوزوکی",
    system: [
      { label: "سامورایی", value: "سامورایی" },
      { label: "سوییفت", value: "سوییفت" },
      { label: "کیزاشی", value: "کیزاشی" },
      { label: "گراند ویتارا 2.0", value: "گراند ویتارا 2.0" },
      { label: "گراند ویتارا 2.4", value: "گراند ویتارا 2.4" },
      { label: "ویتارا (۶ سیلندر)", value: "ویتارا (۶ سیلندر)" },
    ],
  },
  {
    type: "سیتروئن",
    system: [
      { label: "زانتیا", value: "زانتیا" },
      { label: "C3", value: "C3" },
      { label: "C5", value: "C5" },
    ],
  },
  {
    type: "سیناد",
    system: [
      { label: "سیناد 1", value: "سیناد 1" },
      { label: "سیناد 2", value: "سیناد 2" },
      { label: "سیناد کوپه", value: "سیناد کوپه" },
    ],
  },
  {
    type: "شاهین",
    system: [
      { label: "اتوماتیک", value: "اتوماتیک" },
      { label: "دنده ای", value: "دنده ای" },
    ],
  },
  {
    type: "شورلت",
    system: [
      { label: "ایمپالا", value: "ایمپالا" },
      { label: "بلر", value: "بلر" },
      { label: "بلیزر", value: "بلیزر" },
      { label: "تاهو", value: "تاهو" },
      { label: "تراورس", value: "تراورس" },
      { label: "جی ام سی", value: "جی ام سی" },
      { label: "جیمی", value: "جیمی" },
      { label: "رویال", value: "رویال" },
      { label: "سابربرن", value: "سابربرن" },
      { label: "سلبرتی", value: "سلبرتی" },
      { label: "سیلورادو", value: "سیلورادو" },
      { label: "کاپتیوا", value: "کاپتیوا" },
      { label: "کاپریس", value: "کاپریس" },
      { label: "کامارو", value: "کامارو" },
      { label: "کوروت", value: "کوروت" },
      { label: "ملیبو", value: "ملیبو" },
      { label: "مونت کارلو", value: "مونت کارلو" },
      { label: "نوا", value: "نوا" },

    ],
  },
  {
    type: "فراری",
    system: [
      { label: "458 اسپایدر", value: "458 اسپایدر" },
      { label: "458 کوپه", value: "458 کوپه" },
      { label: "F430", value: "F430" },
    ],
  },
  {
    type: "فوتون",
    system: [{ label: "ساوانا", value: "ساوانا" }],
  },
  {
    type: "فورد",
    system: [
      { label: "F150", value: "F150" },
      { label: "F350", value: "F350" },
      { label: "LTD", value: "LTD" },
      { label: "اج", value: "اج" },
      { label: "اسکورت", value: "اسکورت" },
      { label: "اکسپلورر", value: "اکسپلورر" },
      { label: "برانکو", value: "برانکو" },
      { label: "تاروس", value: "تاروس" },
      { label: "تانوس", value: "تانوس" },
      { label: "ترانزیت", value: "ترانزیت" },
      { label: "فوکوس", value: "فوکوس" },
      { label: "فیستا", value: "فیستا" },
      { label: "فیوژن", value: "فیوژن" },
      { label: "گلکسی", value: "گلکسی" },
      { label: "موستانگ", value: "موستانگ" },
    ],
  },
  {
    type: "فولکس",
    system: [
      { label: "بیتل", value: "بیتل" },
      { label: "بیتل کروک", value: "بیتل کروک" },
      { label: "بیتل کوپه", value: "بیتل کوپه" },
      { label: "پاسات (۴ سیلندر)", value: "پاسات (۴ سیلندر)" },
      { label: "پاسات (۵ سیلندر)", value: "پاسات (۵ سیلندر)" },
      { label: "پولو", value: "پولو" },
      { label: "تیگوان", value: "تیگوان" },
      { label: "جتا", value: "جتا" },
      { label: "سانتانا", value: "سانتانا" },
      { label: "سایر", value: "سایر" },
      { label: "شیراکو", value: "شیراکو" },
      { label: "کدی", value: "کدی" },
      { label: "کمپر", value: "کمپر" },
      { label: "گل", value: "گل" },
      { label: "گلف", value: "گلف" },
      { label: "گلف GTI", value: "گلف GTI" },
    ],
  },
  {
    type: "فیات",
    system: [
      { label: "سی ینا", value: "سی ینا" },
      { label: "500", value: "500" },
      { label: "سایر", value: "سایر" },
    ],
  },
  {
    type: "فیدلیتی",
    system: [{ label: "فیدلیتی", value: "فیدلیتی" }],
  },
  {
    type: "لادا",
    system: [
      { label: "کالینا اسپورت", value: "کالینا اسپورت" },
      { label: "گرانتا", value: "گرانتا" },
      { label: "نیوا", value: "نیوا" },
      { label: "سایر", value: "سایر" },
    ],
  },
  {
    type: "لامبورگینی",
    system: [
      { label: "اونتادور", value: "اونتادور" },
      { label: "گالاردو", value: "گالاردو" },
      { label: "هوراکان", value: "هوراکان" },
    ],
  },
  {
    type: "لانچیا",
    system: [{ label: "لانچیا", value: "لانچیا" }],
  },
  {
    type: "لندرور",
    system: [
      { label: "دیسکاوری", value: "دیسکاوری" },
      { label: "دیفندر", value: "دیفندر" },
      { label: "رنجرور", value: "رنجرور" },
      { label: "رنجرور اسپرت", value: "رنجرور اسپرت" },
      { label: "رنجرور ایوک", value: "رنجرور ایوک" },
      { label: "سایر", value: "سایر" },
    ],
  },
  {
    type: "لندمارک",
    system: [
      { label: "اونتادور", value: "اونتادور" },
      { label: "گالاردو", value: "گالاردو" },
      { label: "هوراکان", value: "هوراکان" },
      "77",
    ],
  },
  {
    type: "لوبو",
    system: [{ label: "لوبو", value: "لوبو" }],
  },
  {
    type: "لوتوس",
    system: [
      { label: "الیزه s", value: "الیزه s" },
      { label: "الیزه 220", value: "الیزه 220" },
    ],
  },
  {
    type: "لکسوس",
    system: [
      { label: "CT200H", value: "CT200H" },
      { label: "ES250", value: "ES250" },
      { label: "ES350", value: "ES350" },
      { label: "GS250", value: "GS250" },
      { label: "GS300", value: "GS300" },
      { label: "GS430", value: "GS430" },
      { label: "GS460", value: "GS460" },
      { label: "IS250", value: "IS250" },
      { label: "IS300", value: "IS300" },
      { label: "IS300 کروک", value: "IS300 کروک" },
      { label: "IS350", value: "IS350" },
      { label: "LS400", value: "LS400" },
      { label: "LS460", value: "LS460" },
      { label: "LX570", value: "LX570" },
      { label: "NX200T", value: "NX200T" },
      { label: "NX300H", value: "NX300H" },
      { label: "RX200T", value: "RX200T" },
      { label: "RX350", value: "RX350" },
      { label: "RX450", value: "RX450" },
      { label: "SC430", value: "SC430" },
    ],
  },
  {
    type: "لیفان",
    system: [
      { label: "520", value: "520" },
      { label: "820", value: "820" },
      { label: "620 (1.6)", value: "620 (1.6)" },
      { label: "620 (1.8)", value: "620 (1.8)" },
      { label: "X50", value: "X50" },
      { label: "X60", value: "X60" },
    ],
  },
  {
    type: "لینکن",
    system: [
      { label: "MKX", value: "MKX" },
      { label: "کنتینانتال", value: "کنتینانتال" },
      { label: "نویگیتور", value: "نویگیتور" },
      { label: "سایر", value: "سایر" },
    ],
  },
  {
    type: "مازراتی",
    system: [
      { label: "اسپایدر", value: "اسپایدر" },
      { label: "کواتروپورته", value: "کواتروپورته" },
      { label: "کواتروپورته GTS", value: "کواتروپورته GTS" },
      { label: "کواتروپورته S", value: "کواتروپورته S" },
      { label: "گرن توریسمو", value: "گرن توریسمو" },
      { label: "گرن توریسمو MC", value: "گرن توریسمو MC" },
      { label: "گرن توریسمو S", value: "گرن توریسمو S" },
      { label: "گرن کبریو", value: "گرن کبریو" },
      { label: "گرن کبریو mc", value: "گرن کبریو mc" },
      { label: "گیبلی", value: "گیبلی" },
      { label: "لوانته", value: "لوانته" },
      { label: "لوانتهS", value: "لوانتهS" },
    ],
  },
  {
    type: "مزدا",
    system: [
      { label: "2", value: "2" },
      { label: "3", value: "3" },
      { label: "6", value: "6" },
      { label: "323", value: "323" },
      { label: "626", value: "626" },
      { label: "808", value: "808" },
      { label: "929", value: "929" },
      { label: "3 جدید صندوق دار", value: "3 جدید صندوق دار" },
      { label: "3 جدید هاچ بک", value: "3 جدید هاچ بک" },
      { label: "CX5", value: "CX5" },
      { label: "CX9", value: "CX9" },
      { label: "MX3", value: "MX3" },
      { label: "RX7", value: "RX7" },
    ],
  },
  {
    type: "میتسوبیشی",
    system: [
      { label: "ASX", value: "ASX" },
      { label: "gt3000", value: "gt3000" },
      { label: "اکلیپس", value: "اکلیپس" },
      { label: "اوتلندر", value: "اوتلندر" },
      { label: "اوتلندر PHEV", value: "اوتلندر PHEV" },
      { label: "پاجرو چهار در (۴ سیلندر)", value: "پاجرو چهار در (۴ سیلندر)" },
      { label: "پاجرو چهار در (۶ سیلندر)", value: "پاجرو چهار در (۶ سیلندر)" },
      { label: "پاجرو دو در (۴ سیلندر)", value: "پاجرو دو در (۴ سیلندر)" },
      { label: "پاجرو دو در (۶ سیلندر)", value: "پاجرو دو در (۶ سیلندر)" },
      { label: "زیگما", value: "زیگما" },
      { label: "کلت", value: "کلت" },
      { label: "گالانت (۴ سیلندر)", value: "گالانت (۴ سیلندر)" },
      { label: "گالانت (۶ سیلندر)", value: "گالانت (۶ سیلندر)" },
      { label: "لنسر", value: "لنسر" },
      { label: "میراژ", value: "میراژ" },
    ],
  },
  {
    type: "مینی ماینر",
    system: [
      { label: "کانتری من S", value: "کانتری من S" },
      { label: "کلاب من", value: "کلاب من" },
      { label: "کوپر", value: "کوپر" },
      { label: "کوپر S", value: "کوپر S" },
      { label: "سایر", value: "سایر" },
    ],
  },
  {
    type: "نیسان",
    system: [
      { label: "350Z", value: "350Z" },
      { label: "370Z", value: "370Z" },
      { label: "GT-R", value: "GT-R" },
      { label: "المرا", value: "المرا" },
      { label: "ایکس تریل", value: "ایکس تریل" },
      { label: "آروان", value: "آروان" },
      { label: "آلتیما (۴ سیلندر)", value: "آلتیما (۴ سیلندر)" },
      { label: "آلتیما (۶ سیلندر)", value: "آلتیما (۶ سیلندر)" },
      { label: "پاترول (۴ سیلندر)", value: "پاترول (۴ سیلندر)" },
      { label: "پاترول (۶ سیلندر)", value: "پاترول (۶ سیلندر)" },
      { label: "پت فایندر", value: "پت فایندر" },
      { label: "تی ینا", value: "تی ینا" },
      { label: "تیدا", value: "تیدا" },
      { label: "جوک", value: "جوک" },
      { label: "رونیز", value: "رونیز" },
      { label: "سانی", value: "سانی" },
      { label: "سرانزا", value: "سرانزا" },
      { label: "قشقایی", value: "قشقایی" },
      { label: "ماکسیما", value: "ماکسیما" },
      { label: "مورانو", value: "مورانو" },
      { label: "میکرا", value: "میکرا" },
      { label: "ورسا", value: "ورسا" },
    ],
  },
  {
    type: "هامر",
    system: [
      { label: "H2", value: "H2" },
      { label: "H3", value: "H3" },
      { label: "141", value: "141" },
    ],
  },
  {
    type: "هاوال",
    system: [
      { label: "H2", value: "H2" },
      { label: "H6", value: "H6" },
      { label: "H8", value: "H8" },
      { label: "H9", value: "H9" },
    ],
  },
  {
    type: "هایما",
    system: [
      { label: "S5", value: "S5" },
      { label: "S7", value: "S7" },
    ],
  },
  {
    type: "هن تنگ",
    system: [
      { label: "X5", value: "X5" },
      { label: "X7", value: "X7" },
    ],
  },
  {
    type: "هوندا",
    system: [
      { label: "CR-V", value: "CR-V" },
      { label: "CR-X", value: "CR-X" },
      { label: "HR-V", value: "HR-V" },
      { label: "S800", value: "S800" },
      { label: "آکورد", value: "آکورد" },
      { label: "آکورد کوپه", value: "آکورد کوپه" },
      { label: "سیتی", value: "سیتی" },
      { label: "سیویک", value: "سیویک" },
    ],
  },
  {
    type: "هیلمن",
    system: [{ label: "اونجر", value: "اونجر" }],
  },
  {
    type: "ولوو",
    system: [
      { label: "C30", value: "C30" },
      { label: "C70 کروک", value: "C70 کروک" },
      { label: "V40", value: "V40" },
      { label: "XC60", value: "XC60" },
      { label: "XC90", value: "XC90" },
      { label: "سایر", value: "سایر" },
    ],
  },
  {
    type: "پاژن",
    system: [
      { label: "4 سیلندر", value: "4 سیلندر" },
      { label: "6 سیلندر", value: "6 سیلندر" },
    ],
  },
  {
    type: "پروتون",
    system: [
      { label: "ایمپیان", value: "ایمپیان" },
      { label: "جن تو", value: "جن تو" },
      { label: "ویرا", value: "ویرا" },
    ],
  },
  {
    type: "پلیموث",
    system: [{ label: "پلیموث", value: "پلیموث" }],
  },
  {
    type: "پورشه",
    system: [
      { label: "911", value: "911" },
      { label: "911 توربو", value: "911 توربو" },
      { label: "911 کررا ۴", value: "911 کررا ۴" },
      { label: "911 کررا s", value: "911 کررا s" },
      { label: "باکستر", value: "باکستر" },
      { label: "باکستر ۷۱۸", value: "باکستر ۷۱۸" },
      { label: "باکستر ۷۱۸ s", value: "باکستر ۷۱۸ s" },
      { label: "باکستر s", value: "باکستر s" },
      { label: "پانامرا", value: "پانامرا" },
      { label: "پانامرا 4S", value: "پانامرا 4S" },
      { label: "پانامرا توربو", value: "پانامرا توربو" },
      { label: "کاین", value: "کاین" },
      { label: "کاین توربو", value: "کاین توربو" },
      { label: "کیمن S", value: "کیمن S" },
      { label: "ماکان", value: "ماکان" },
    ],
  },
  {
    type: "پونتیانگ",
    system: [
      { label: "استر", value: "استر" },
      { label: "پاریزین", value: "پاریزین" },
      { label: "ترنس ام", value: "ترنس ام" },
      { label: "فایربرد", value: "فایربرد" },
      { label: "کاتالینا", value: "کاتالینا" },
      { label: "گراندویل", value: "گراندویل" },
      { label: "گرند ام", value: "گرند ام" },
      { label: "گرند پریکس", value: "گرند پریکس" },
      { label: "لمانز", value: "لمانز" },
    ],
  },
  {
    type: "پیکان",
    system: [{ label: "پیکان", value: "پیکان" }],
  },
  {
    type: "چانگان",
    system: [
      { label: "CS 35", value: "CS 35" },
      { label: "ایدو", value: "ایدو" },
    ],
  },
  {
    type: "چری",
    system: [
      { label: "A15", value: "A15" },
      { label: "آریزو 5", value: "آریزو 5" },
      { label: "آریزو 5TE", value: "آریزو 5TE" },
      { label: "آریزو 6", value: "آریزو 6" },
      { label: "تیگو 5", value: "تیگو 5" },
      { label: "تیگو 7", value: "تیگو 7" },
      { label: "ویانا", value: "ویانا" },
    ],
  },
  {
    type: "کادیلاک",
    system: [
      { label: "ATS", value: "ATS" },
      { label: "CTS", value: "CTS" },
      { label: "SRX", value: "SRX" },
      { label: "اسکلید", value: "اسکلید" },
      { label: "الدورادو", value: "الدورادو" },
      { label: "دویل", value: "دویل" },
      { label: "سویل", value: "سویل" },
      { label: "فلیت وود", value: "فلیت وود" },
    ],
  },
  {
    type: "کرایسلر",
    system: [
      { label: "300C", value: "300C" },
      { label: "300M", value: "300M" },
      { label: "سایر", value: "سایر" },
    ],
  },
  {
    type: "کوپا",
    system: [{ label: "کوپا", value: "کوپا" }],
  },
  {
    type: "کوییک",
    system: [
      { label: "آر", value: "آر" },
      { label: "فول", value: "فول" },
      { label: "پایه", value: "پایه" },
      { label: "پلاس", value: "پلاس" },
    ],
  },
  {
    type: "گریت وال",
    system: [
      { label: "ولکس C30 اتوماتیک", value: "ولکس C30 اتوماتیک" },
      { label: "ولکس C30 دنده ای", value: "ولکس C30 دنده ای" },
      { label: "وینگل 5", value: "وینگل 5" },
      { label: "هاوال H6", value: "هاوال H6" },
      { label: "هاوال M4", value: "هاوال M4" },
    ],
  },
  {
    type: "گک گونو",
    system: [
      { label: "G5", value: "G5" },
      { label: "ترامپچی GA3S", value: "ترامپچی GA3S" },
      { label: "ترامپچی GS4", value: "ترامپچی GS4" },
      { label: "ترامپچی GS5", value: "ترامپچی GS5" },
    ],
  },
];

// store.dispatch(updateLoadingPercent(0));
// Axios.request(
//   {
//   method,
//   url,
//   headers,
//   ...options,
//   data: body,
//   withCredentials: true,
//   onDownloadProgress: (progressEvent) => {
//     let percentage = Math.round(
//       (progressEvent.loaded * 100) / progressEvent.total
//     );
//     // store.dispatch(updateLoadingPercent(percentage));
//   },
//   onUploadProgress: (progressEvent) => {
//     let percentage = Math.round(
//       (progressEvent.loaded * 100) / progressEvent.total
//     );
//     // store.dispatch(updateLoadingPercent(percentage));
//   },
// })
